//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BookTB
{
    public BookTB()
    {
        this.Carts = new HashSet<Cart>();
    }

    public int Id { get; set; }
    public int TypeID { get; set; }
    public string Name { get; set; }
    public double Price { get; set; }
    public string Description { get; set; }
    public string Image { get; set; }
    public string author { get; set; }

    public virtual BookType BookType { get; set; }
    public virtual ICollection<Cart> Carts { get; set; }
}

public partial class BookType
{
    public BookType()
    {
        this.BookTBs = new HashSet<BookTB>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<BookTB> BookTBs { get; set; }
}

public partial class Cart
{
    public int ID { get; set; }
    public string ClientID { get; set; }
    public int ProductID { get; set; }
    public int Amount { get; set; }
    public Nullable<System.DateTime> DatePurchased { get; set; }
    public bool IsInCart { get; set; }

    public virtual BookTB BookTB { get; set; }
}

public partial class order
{
    public int id { get; set; }
    public string client { get; set; }
    public string product { get; set; }
    public int amount { get; set; }
    public double price { get; set; }
    public System.DateTime date { get; set; }
    public bool orderShipped { get; set; }

    public virtual order orders1 { get; set; }
    public virtual order order1 { get; set; }
}

public partial class UserDetail
{
    public int Id { get; set; }
    public string Guid { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public int PostalCode { get; set; }
}
